Feature/dmps dm fixes
PepperDash/Essentials pull request #957
Opened 2022-06-14 15:12 UTC by alex-johnson

There are a variety of DMPS and general DM fixes in this PR

[x] I switched the DMPS initialization hold at boot to only wait for devices to be registered, not to wait for everything to be activated. This will happen quicker but still meet the needs of waiting to register the DMPS until after DM endpoints are created.
[x] Added support for HD-MD-8x2 type switchers. These are older and somewhat unique hardware so I created a new class for it.
[x] Added an output to DM chassis join map for the device name
[x] Removed a redundant check for the DMPS-4K type unit. This already existed at a global level
[x] Added digital audio outputs on the DMPS and the ability to bridge them to SIMPL.
[x] Added ability to recall Equalizer presets on DMPS
[x] Added recalling the startup volume when recalling a preset on a DMPS3 (non-4K only). The presets do not affect the main volume fader, so this makes it behave more like the newer DMPS units.
[x] This fixes the online feedback at the Tx or Rx level for DM endpoints on a DM-CPU3 chassis or a DMPS3-4K chassis. In those cases, the device itself doesn't know the online status. The online feedback has to come from the chassis. This required changing CrestronGenericBaseDevice `public BoolFeedback IsOnline { get; private set; }` to `public BoolFeedback IsOnline { get; set; }`. If there is a better way to override that, I can try to implement.
[x] Reworks audio routing on the DMPS3-4K, which on the Crestron side is a bit messy with the weird indexing and an enum for the audio feedback that doesn't line up well with anything. This also happens to resolve #689 and you can now bridge and route to the digital outputs for HDMI and DM out.
[x] Improves support for DMPS3-4K-150 series as those use different classes for things

2022-06-29 16:58 UTC, ndorin requested changes

2022-06-30 00:26 UTC, alex-johnson commented on essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron/CrestronGenericBaseDevice.cs
> +		public BoolFeedback IsOnline { get; set; }
Understood - I'll work on implementing that

2022-08-05 14:52 UTC, alex-johnson commented on essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron/CrestronGenericBaseDevice.cs
> +		public BoolFeedback IsOnline { get; set; }
Okay I think I have a fix using the IsOnline.SetValueFunc() that would keep the setter on IsOnline private. I'll test it out with some devices first.

2022-08-12 13:40 UTC, alex-johnson commented
The requested changes are implemented and I believe this is ready. The latest update also adds offline feedback and endpoint name feedback to join maps for DM endpoints that didn't have it already.

2022-09-02 14:54 UTC, ndorin approved these changes

2022-09-02 17:00 UTC, merged